spring:
  application:
    name: notification-service
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
          notification-in:
            destination: notification
            contentType: application/json
          notification-out:
            destination: notification
            contentType: application/json

server:
  port: 6262

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
