### Spring properties
# Service registers under this name
spring:
  application:
    name: account-service
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
       prefer-ip-address: true

# HTTP Server (Tomcat) Port
server: 
  port: 6060

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
   
spring.zipkin.baseUrl: http://localhost:9411/    