# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client: 
    registerWithEureka: false
    fetchRegistry: false

# HTTP (Tomcat) port
server:
  port: 8761    