spring:
  application:
    name: spring-cloud-ribbon-client

server:
  port: 8181

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
