server:
  port: 8888

spring:
  application:
          name: app-config-repo

  cloud:
    config:
      server:
          git: 
            uri:  https://github.com/dineshonjava/app-config-repo
            username: arnav
            password: sweety
            